version: 2
jobs:
  master:
    docker:
      - image: circleci/php:7.0
    steps:
     - checkout
     
  staging:
    docker:
      - image: circleci/php:7.0
    steps:
     - checkout
     
  dev:
    docker:
      - image: circleci/php:7.0
    steps:
     - checkout
     #- run: echo "A first hello"
  #deploy:
  #  machine:
  #    enabled: true
  #  steps:
  #    - run:
  #        name: Deploy Over SSH
  #        command: |
  #          ssh $SSH_USER@$SSH_HOST "<remote deploy command>"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - master
          filters:
            branches:
              only: master
      - staging
          filters:
            branches:
              only: staging  
      - dev
          filters:
            branches:
              only: /.*/
      #- deploy:
      #    requires:
      #      - build
      #    filters:
      #      branches:
      #        only: master
