version: 2
jobs:     
  master:
   docker:
     - image: circleci/php:5.6
   steps:
    - checkout
   

workflows:
  version: 2
  deployment:
    jobs:
      - master:
        filters:
          branches:
            only: master
