version: 2
jobs:     
  master:
    docker:
      - image: circleci/php:7.0
    steps:
     - checkout
           
  staging:
    docker:
      - image: circleci/php:7.0
    steps:
     - checkout
           
  development:
    branches:
        ignore:
          - master
          - staging
    docker:
      - image: circleci/php:7.0
    steps:
     - checkout

workflows:
  version: 2
  deployment:
    jobs:
      - master:
         filters:
           branches:
             only: master
      - staging:
         filters:
           branches:
             only: staging
      - development
        
