version: 2
jobs:           
  development:
    docker:
      - image: circleci/php:7.0
    steps:
     - checkout
     - run: sh ./sh/deploy.sh $CIRCLE_BRANCH

workflows:
  version: 2
  deployment:
    jobs:
      - development
        