version: 2
jobs:           
  development:
    docker:
      - image: circleci/php:7.0
    steps:
     - checkout
     - run:
          name: Deploy Over SSH
          command: |
            ssh -o 'StrictHostKeyChecking=no' $SSH_USER@$SSH_HOST -p 21 mkdir -p /home/$CIRCLE_BRANCH

workflows:
  version: 2
  deployment:
    jobs:
      - development
       